root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd/api"
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules"]
exclude_regex = ["_test\\.go"]
stop_on_error = true
poll = true
poll_interval = 1000

[log]
time = true
main_only = false
silent = false

[screen]
clear_on_rebuild = true
keep_scroll = true
